import type { CatalogHomeSettings, CatalogProduct } from "@/lib/catalog-storefront/types";

export const DEFAULT_CATALOG_HOME: CatalogHomeSettings = {
  eyebrow: "CATÁLOGO TERRA",
  title: "Encuentra el descanso que buscas.",
  description: "Explora los productos disponibles y conversa con Terra por WhatsApp para recibir atención directa.",
  imageUrl: null,
};

/**
 * Solo se usa durante desarrollo si la base de catálogo todavía no fue migrada.
 * Nunca se entrega al público en producción: evita publicar productos ficticios.
 */
export const DEVELOPMENT_CATALOG_PREVIEW: CatalogProduct[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    externalCode: null,
    slug: "producto-terra-01",
    name: "Producto Terra 01",
    category: "Colchones",
    shortDescription: "Espacio preparado para tu próximo colchón.",
    description: "Completa esta ficha desde el panel privado con la información comercial, medidas y fotos reales.",
    specifications: ["Ficha técnica pendiente", "Imagen pendiente"],
    priceFrom: null,
    compareAtPriceFrom: null,
    availability: "coming_soon",
    published: false,
    featured: true,
    sortOrder: 1,
    images: [],
    variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    externalCode: null,
    slug: "producto-terra-02",
    name: "Producto Terra 02",
    category: "Colchones",
    shortDescription: "Espacio preparado para un segundo modelo.",
    description: "Completa esta ficha desde el panel privado antes de publicarla.",
    specifications: ["Ficha técnica pendiente", "Imagen pendiente"],
    priceFrom: null,
    compareAtPriceFrom: null,
    availability: "coming_soon",
    published: false,
    featured: false,
    sortOrder: 2,
    images: [],
    variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    externalCode: null,
    slug: "producto-terra-03",
    name: "Producto Terra 03",
    category: "Almohadas",
    shortDescription: "Espacio preparado para una almohada o accesorio.",
    description: "Completa esta ficha desde el panel privado antes de publicarla.",
    specifications: ["Ficha técnica pendiente", "Imagen pendiente"],
    priceFrom: null,
    compareAtPriceFrom: null,
    availability: "coming_soon",
    published: false,
    featured: false,
    sortOrder: 3,
    images: [],
    variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    externalCode: null,
    slug: "producto-terra-04",
    name: "Producto Terra 04",
    category: "Almohadas",
    shortDescription: "Espacio preparado para un cuarto producto.",
    description: "Completa esta ficha desde el panel privado antes de publicarla.",
    specifications: ["Ficha técnica pendiente", "Imagen pendiente"],
    priceFrom: null,
    compareAtPriceFrom: null,
    availability: "coming_soon",
    published: false,
    featured: false,
    sortOrder: 4,
    images: [],
    variants: [],
  },
];
