import type {
  CatalogHomeSettings,
  CatalogProduct,
} from "@/lib/catalog-storefront/types";

export const DEFAULT_CATALOG_HOME: CatalogHomeSettings = {
  eyebrow: "CATÁLOGO TERRA",
  title: "Encuentra el descanso que buscas.",
  description:
    "Explora los productos disponibles y conversa con Terra por WhatsApp para recibir atención directa.",
  imageUrl: null,
};

/**
 * Solo se usa durante desarrollo si la base de catálogo todavía no fue migrada.
 * Nunca se entrega al público en producción: evita publicar productos ficticios.
 */
export const DEVELOPMENT_CATALOG_PREVIEW: CatalogProduct[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    externalCode: null,
    slug: "producto-terra-01",
    name: "Colchón Terra Aura",
    category: "Colchones",
    shortDescription:
      "Ejemplo local de una familia con versiones públicas y selectores independientes.",
    description:
      "Cada versión conserva su propia página, precio, código y galería. La descripción y los detalles se comparten dentro de la familia.",
    specifications: [
      "Selector de tamaño opcional",
      "Selector de color opcional",
      "Galería por versión: hasta 3 fotos",
    ],
    priceFrom: 1200,
    compareAtPriceFrom: null,
    availability: "available",
    published: true,
    featured: true,
    sortOrder: 1,
    images: [],
    variants: [
      {
        id: "00000000-0000-4000-8000-000000000011",
        externalCode: "T-AURA-15-ALM",
        name: "Colchón Terra Aura Almendra",
        slug: "producto-terra-01",
        label: "1.5 plazas",
        colorHex: "#b68a62",
        colorName: "Almendra",
        showColor: true,
        showOptionText: true,
        isPrimary: true,
        price: 1200,
        compareAtPrice: null,
        availability: "available",
        active: true,
        sortOrder: 0,
        images: [],
      },
      {
        id: "00000000-0000-4000-8000-000000000012",
        externalCode: "T-AURA-15-CRU",
        name: "Colchón Terra Aura Crudo",
        slug: "producto-terra-01-crudo",
        label: "1.5 plazas",
        colorHex: "#e7ddca",
        colorName: "Crudo",
        showColor: true,
        showOptionText: true,
        isPrimary: false,
        price: 1250,
        compareAtPrice: null,
        availability: "available",
        active: true,
        sortOrder: 1,
        images: [],
      },
      {
        id: "00000000-0000-4000-8000-000000000013",
        externalCode: "T-AURA-20-ALM",
        name: "Colchón Terra Aura 2 plazas",
        slug: "producto-terra-01-2-plazas",
        label: "2 plazas",
        colorHex: "#b68a62",
        colorName: "Almendra",
        showColor: true,
        showOptionText: true,
        isPrimary: false,
        price: 1400,
        compareAtPrice: null,
        availability: "available",
        active: true,
        sortOrder: 2,
        images: [],
      },
    ],
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    externalCode: null,
    slug: "producto-terra-02",
    name: "Producto Terra 02",
    category: "Colchones",
    shortDescription: "Espacio preparado para un segundo modelo.",
    description:
      "Completa esta ficha desde el panel privado antes de publicarla.",
    specifications: ["Ficha técnica pendiente", "Imagen pendiente"],
    priceFrom: null,
    compareAtPriceFrom: null,
    availability: "coming_soon",
    published: false,
    featured: false,
    sortOrder: 2,
    images: [],
    variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    externalCode: null,
    slug: "producto-terra-03",
    name: "Producto Terra 03",
    category: "Almohadas",
    shortDescription: "Espacio preparado para una almohada o accesorio.",
    description:
      "Completa esta ficha desde el panel privado antes de publicarla.",
    specifications: ["Ficha técnica pendiente", "Imagen pendiente"],
    priceFrom: null,
    compareAtPriceFrom: null,
    availability: "coming_soon",
    published: false,
    featured: false,
    sortOrder: 3,
    images: [],
    variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    externalCode: null,
    slug: "producto-terra-04",
    name: "Producto Terra 04",
    category: "Almohadas",
    shortDescription: "Espacio preparado para un cuarto producto.",
    description:
      "Completa esta ficha desde el panel privado antes de publicarla.",
    specifications: ["Ficha técnica pendiente", "Imagen pendiente"],
    priceFrom: null,
    compareAtPriceFrom: null,
    availability: "coming_soon",
    published: false,
    featured: false,
    sortOrder: 4,
    images: [],
    variants: [],
  },
];
